### ISSUE TITLE
Unable to authenticate with local service

### ISSUE THREAD

**Issue by mcheck** [simojenki/bonob#122]
Thank you for this software, excited to get it running.
Using a Docker container with full Sonos device auto-discovery and auto-registration on port 3000 and using one of my speakers as a seed device, I successfully register the bonob service.

The first time I selected it, it asked for authentication. I thought this is the local Sonos authentication account.
I entered that and it gave me a network error - I cannot get back to the screen to re-enter credentials (whatever they may be).
"Try again" brings me back to the screen. "Not now" clears closes the window.

Despite restarting and resetting the BONOB services as different containers, and settings, selection of the service always gives me the Error screen.

![image](https://user-images.githubusercontent.com/196895/201419948-671db45b-1185-44ce-8eb8-2150a785df0a.png)

**Comment by simojenki** [comment]
It looks like you are using a Mac?, I've never tested it that way, so cannot be sure it works.
Do you have an iPhone handy that you can authenticate with?

**Comment by mcheck** [comment]
Yes, running docker on an Intel Mac.
I do have an iphone, I'll try that. Assuming authentication is the Sonos credentials?

**Comment by simojenki** [comment]
Auth is your navidrome credentials

**Comment by simojenki** [comment]
Did this work?

**Comment by mcheck** [comment]
Thanks for following up. Unfortunately, for now, I had to move on. I'll be
able to dedicate more time to it in the near future.

**Comment by jdewoody71** [comment]
I'm having the same exact issue. It happens with Sonos Windows controller or Sonos app on Android phone. The service registers successfully. I've tried both host and bridge networking with no luck. Any help would be greatly appreciated.
![image](https://user-images.githubusercontent.com/31523590/236511383-a4020212-5070-46fb-bd9b-24616f8be63a.png)
![image](https://user-images.githubusercontent.com/31523590/236511547-1974fe07-03e8-4225-aaa9-fddd892dcead.png)

**Comment by simojenki** [comment]
What happens if you put the following URLs into your browser;
http://172.16.0.250:4533
http://172.17.0.250:4534

Do both of them resolve to either ND or BNB from your desktop browser?

Those IP addresses look like internet docker networking IPs, you need to use an IP or host name that is available on your network

**Comment by jdewoody71** [comment]
My home network is 172.16.0.x, a class B private network. 

They both load fine if I click on them.  I can register and unregister without issue as well from the bonob URL.

**Comment by simojenki** [comment]
And 172.17.0.x?  Is that another local network?

**Comment by simojenki** [comment]
I presume that .17 can connect to .16?

Can the Sonos devices connect to the .17?

**Comment by jdewoody71** [comment]
> And 172.17.0.x? Is that another local network?

Yes, that's the docker's internal network. This is running in unRAID.

**Comment by jdewoody71** [comment]
> I presume that .17 can connect to .16?
> 
> Can the Sonos devices connect to the .17?

Yes. I have several dockers with the 172.17.x.x network and they work fine.

They did previously when I used to use Roon. Airsonic worked at one time as well. I don't know a way to ping from the Sonos device.

**Comment by simojenki** [comment]
The BNB_URL value must be accessible from the Sonos devices themselves.  Can you try changing that to be on the .16 subnet (port forward?), rather than the internal docker network.

**Comment by jdewoody71** [comment]
Unfortunately, I've already tried both and the results are the same.

**Comment by mrasmith** [comment]
I seem to have the same issue, installed on docker. My ENV looks like this ...

![bonob](https://github.com/simojenki/bonob/assets/33915950/8e08d7e4-a94a-4912-9d0e-d1f6bbe690cb)

I never get to a login page for Navidrome. I've tried both the external https url for my Navidrone and the local address at 192.168.1.50:4533


https://github.com/simojenki/bonob/assets/33915950/66bafe59-e49b-4981-a14f-201b9f884849

**Comment by miziodel** [comment]
> I seem to have the same issue, installed on docker. My ENV looks like this ...
> 
> I never get to a login page for Navidrome. I've tried both the external https url for my Navidrone and the local address at 192.168.1.50:4533
> 

I seem to have the same problem :(

**Comment by miziodel** [comment]
and after some cross double checks, don't tell me why, but I discovered that in the BNB_URL I had specified the HTTPS protocol, while it should have been HTTP.. after I fixed this config, everything worked out. thanks!

**Comment by mrasmith** [comment]
> and after some cross double checks, don't tell me why, but I discovered that in the BNB_URL I had specified the HTTPS protocol, while it should have been HTTP.. after I fixed this config, everything worked out. thanks!

I still can't get it to work on my system, would you mind sharing all your ENV parameters?
